export class StockDto{
    stockBoughtDate:String;
    stockEndDate?:String;
    totalUnits:Number;
    id?:Number;
    unitsSold?:Number;
    unitsLeft?:Number;
    createdUser?:String;
    updatedUser?:String;
    productid:Number;
    stock_Sku:String;
    productName:String;
    category?:String;
    ordersRecieved?:Number;
    salePrice?:String;
    MRPPrice?:String;
    productDesc?:String;
    categoryId?:Number;
}