import { Table, Model, Column, DataType } from 'sequelize-typescript';
import { Col } from 'sequelize/types/lib/utils';
@Table
export class Stock extends Model{
    @Column({
        type:DataType.STRING
    })
    stockBoughtDate:String
    @Column({
        type:DataType.STRING
    })
    stockEndDate:String
    @Column({
        type:DataType.INTEGER
    })
    totalUnits:Number
    @Column({
        type:DataType.INTEGER,
        autoIncrement:true,
        primaryKey:true
    })
    id:Number
    @Column({
        type:DataType.INTEGER
    })
    unitsSold:Number
    @Column({
        type:DataType.INTEGER
    })
    unitsLeft:Number
    @Column({
        type:DataType.STRING
    })
    createdUser:String
    @Column({
        type:DataType.STRING
    })
    updatedUser:String
    @Column({
        type:DataType.INTEGER
    })
    productid:String
    @Column({
        type:DataType.STRING
    })
    stock_Sku:String
    @Column({
        type:DataType.STRING
    })
    category:String
    @Column({
        type:DataType.INTEGER
    })
    ordersRecieved:Number
    @Column({
        type:DataType.STRING
    })
    salePrice:String;
    @Column({
        type:DataType.STRING
    })
    MRPPrice:String;
    @Column({
        type:DataType.STRING
    })
    deleteInd:String
    @Column({
        type:DataType.STRING
    })
    productName:String
    @Column({
        type:DataType.STRING
    })
    productDesc:String
}